import { z } from 'zod';
import { StatusBadgeField } from '../fields/status-badge-field';

export const fieldSetConfig = {
  name: 'Field Set',
  actionPrefix: 'fieldSet',
  displayFields: [
    { key: 'name', label: 'Name', clickable: true },
    { key: 'description', label: 'Description' },
    { key: 'configurations', label: 'Configurations', render: StatusBadgeField },
    { key: 'isDefault', label: 'Default' }
  ],
  searchFields: ['name', 'description'],
  createFields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'isDefault', label: 'Set as Default', type: 'checkbox' }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    description: z.string().optional(),
    isDefault: z.boolean().optional()
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export fieldSetHandlers anymore 