import { z } from 'zod';
import { IconField } from '../fields/icon-field';
import { StatusBadgeField } from '../fields/status-badge-field';

export const issueTypeConfig = {
  name: 'Issue Type',
  actionPrefix: 'issueType',
  displayFields: [
    { key: 'icon', label: 'Icon', render: IconField },
    { key: 'name', label: 'Name' },
    { key: 'description', label: 'Description' },
  ],
  searchFields: ['name', 'description'],
  createFields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'icon', label: 'Icon & Color', type: 'icon' },
    { key: 'statusFlowId', label: 'Status Flow', type: 'select', required: true },
    { key: 'fieldSetId', label: 'Field Set', type: 'select', required: true }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    description: z.string().optional(),
    icon: z.string().optional(),
    statusFlowId: z.string().min(1, 'Status flow is required'),
    fieldSetId: z.string().min(1, 'Field set is required')
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export issueTypeHandlers anymore 