import { z } from 'zod';
import { ColorField } from '../fields/color-field';
import { StatusBadgeField } from '../fields/status-badge-field';

export const labelConfig = {
  name: 'Label',
  actionPrefix: 'label',
  displayFields: [
    { key: 'name', label: 'Name', clickable: true },
    { key: 'color', label: 'Color', render: ColorField },
    { key: 'description', label: 'Description' },
    { key: 'group', label: 'Group', render: StatusBadgeField }
  ],
  searchFields: ['name', 'description'],
  createFields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'color', label: 'Color', type: 'color' },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'groupId', label: 'Group', type: 'select' }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    color: z.string().optional(),
    description: z.string().optional(),
    groupId: z.string().optional()
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export labelHandlers anymore 