import { z } from 'zod';
import { IconField } from '../fields/icon-field';
import { TeamAccordionField } from '../fields/team-accordion-field';
import { StatusBadgeField } from '../fields/status-badge-field';

export const memberConfig = {
  name: 'Member',
  actionPrefix: 'member',
  displayFields: [
    { key: 'icon', label: 'Icon', render: IconField },
    { key: 'email', label: 'Email', clickable: true },
    { key: 'name', label: 'First Name' },
    { key: 'lastName', label: 'Last Name' },
    { key: 'displayName', label: 'Display Name' },
    { key: 'teams', label: 'Teams', render: TeamAccordionField },
    { key: 'status', label: 'Status', render: StatusBadgeField }
  ],
  searchFields: ['name', 'lastName', 'email', 'displayName'],
  createFields: [
    { key: 'name', label: 'First Name', type: 'text', required: true },
    { key: 'lastName', label: 'Last Name', type: 'text', required: true },
    { key: 'displayName', label: 'Display Name', type: 'text' },
    { key: 'email', label: 'Email', type: 'email', required: true },
    { key: 'role', label: 'Role', type: 'select', required: true }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'First name required'),
    lastName: z.string().min(1, 'Last name required'),
    email: z.string().email('Invalid email'),
    role: z.enum(['OWNER', 'ADMIN', 'MEMBER', 'GUEST']),
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export memberHandlers anymore 