import { z } from 'zod';
import { IconField } from '../fields/icon-field';
import { StatusBadgeField } from '../fields/status-badge-field';

export const projectConfig = {
  name: 'Project',
  actionPrefix: 'project',
  displayFields: [
    { key: 'icon', label: 'Icon', render: IconField },
    { key: 'name', label: 'Name', clickable: true },
    { key: 'identifier', label: 'Identifier' },
    { key: 'summary', label: 'Summary' },
    { key: 'status', label: 'Status', render: StatusBadgeField },
    { key: 'createdAt', label: 'Created' }
  ],
  searchFields: ['name', 'identifier', 'description', 'summary'],
  createFields: [
    { key: 'icon', label: 'Icon & Color', type: 'icon' },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'identifier', label: 'Identifier', type: 'text', required: true },
    { key: 'summary', label: 'Summary', type: 'text' },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'color', label: 'Color', type: 'color' },
    { key: 'status', label: 'Status', type: 'select', required: true },
    { key: 'teamId', label: 'Lead Team', type: 'select', required: true, options: { actionPrefix: 'team' } }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    identifier: z.string().min(1, 'Identifier is required'),
    summary: z.string().optional(),
    description: z.string().optional(),
    icon: z.string().optional(),
    color: z.string().optional(),
    status: z.enum(['ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELED']).default('ACTIVE'),
    teamId: z.string().min(1, 'Lead team is required')
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export projectHandlers anymore 