import { z } from 'zod';

export const stateConfig = {
  name: 'State',
  actionPrefix: 'state',
  displayFields: [
    { key: 'name', label: 'Name', clickable: true },
    { key: 'description', label: 'Description' },
    { key: 'color', label: 'Color' },
    { key: 'type', label: 'Type' },
    { key: 'position', label: 'Position' }
  ],
  searchFields: ['name', 'description'],
  createFields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'color', label: 'Color', type: 'color', required: true },
    { key: 'type', label: 'Type', type: 'select', required: true },
    { key: 'position', label: 'Position', type: 'number' },
    { key: 'statusFlowId', label: 'Status Flow', type: 'select', required: true }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    description: z.string().optional(),
    color: z.string().min(1, 'Color is required'),
    type: z.enum(['BACKLOG', 'UNSTARTED', 'STARTED', 'COMPLETED', 'CANCELED']),
    position: z.number().optional(),
    statusFlowId: z.string().min(1, 'Status Flow is required')
  })
};

// Handlers are now auto-generated by DatabaseFactory! 