import { z } from 'zod';
import { ColorField } from '../fields/color-field';
import { StatusBadgeField } from '../fields/status-badge-field';
import { StatusFlowEditorWrapper } from './status-flow-editor-wrapper';

export const statusFlowConfig = {
  name: 'Status Flow',
  actionPrefix: 'statusFlow',
  displayFields: [
    { key: 'name', label: 'Name', clickable: true },
    { key: 'description', label: 'Description' },
    { key: 'states', label: 'States', render: StatusBadgeField },
    { key: 'isDefault', label: 'Default' }
  ],
  searchFields: ['name', 'description'],
  createFields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'isDefault', label: 'Set as Default', type: 'checkbox' }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    description: z.string().optional(),
    isDefault: z.boolean().optional()
  }),
  customEditor: StatusFlowEditorWrapper
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export statusFlowHandlers anymore 