import { z } from 'zod';
import { IconField } from '../fields/icon-field';
import { StatusBadgeField } from '../fields/status-badge-field';

export const teamConfig = {
  name: 'Team',
  actionPrefix: 'team',
  displayFields: [
    { key: 'icon', label: 'Icon', render: IconField },
    { key: 'name', label: 'Name', clickable: true },
    { key: 'identifier', label: 'Identifier' },
    { key: 'timezone', label: 'Timezone' },
    { key: 'isPrivate', label: 'Private', render: StatusBadgeField },
    { key: 'createdAt', label: 'Created' }
  ],
  searchFields: ['name', 'identifier', 'description'],
  createFields: [
    { key: 'icon', label: 'Icon & Color', type: 'icon' },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'identifier', label: 'Identifier', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'timezone', label: 'Time Zone', type: 'timezone' },
    { key: 'isPrivate', label: 'Private Team', type: 'checkbox' }
  ],
  validationSchema: z.object({
    name: z.string().min(1, 'Name is required'),
    identifier: z.string().min(1, 'Identifier is required'),
    description: z.string().optional(),
    icon: z.string().optional(),
    timezone: z.string().optional(),
    isPrivate: z.boolean().optional()
  }),
  // customActions and customFieldRenderers can be added here as needed
};

// Handlers are now auto-generated by DatabaseFactory!
// No need to manually export teamHandlers anymore 