-- Drop old icon columns if they exist
ALTER TABLE "User"
DROP COLUMN IF EXISTS "icon",
DROP COLUMN IF EXISTS "iconColor";

ALTER TABLE "Workspace"
DROP COLUMN IF EXISTS "icon",
DROP COLUMN IF EXISTS "iconColor";

ALTER TABLE "Team"
DROP COLUMN IF EXISTS "icon",
DROP COLUMN IF EXISTS "iconColor";

-- Ensure avatar columns exist
ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "avatarType" TEXT NOT NULL DEFAULT 'initials',
ADD COLUMN IF NOT EXISTS "avatarIcon" TEXT,
ADD COLUMN IF NOT EXISTS "avatarColor" TEXT,
ADD COLUMN IF NOT EXISTS "avatarImageUrl" TEXT;

ALTER TABLE "Workspace"
ADD COLUMN IF NOT EXISTS "avatarType" TEXT NOT NULL DEFAULT 'initials',
ADD COLUMN IF NOT EXISTS "avatarIcon" TEXT,
ADD COLUMN IF NOT EXISTS "avatarColor" TEXT,
ADD COLUMN IF NOT EXISTS "avatarImageUrl" TEXT;

ALTER TABLE "Team"
ADD COLUMN IF NOT EXISTS "avatarType" TEXT NOT NULL DEFAULT 'initials',
ADD COLUMN IF NOT EXISTS "avatarIcon" TEXT,
ADD COLUMN IF NOT EXISTS "avatarColor" TEXT,
ADD COLUMN IF NOT EXISTS "avatarImageUrl" TEXT; 